CREATE TABLE `изготовители` (
  `код` INT NOT NULL,
  `название` VARCHAR(255) DEFAULT NULL,
  `страна` VARCHAR(50) DEFAULT NULL,
  `сайт` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (код)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;